### PR TITLE
Add isomorphic-fetch to tests

### PR DESCRIPTION
**Pull request by Hughp135**
Add isomorphic-fetch to the package.json and mocharc.json so that fetch is available in the node environment.
Feel free to close this PR if you don't want to support LTS version of node.

image

### CODE REVIEW

**Comment by AnonymerNiklasistanonym** [comment]
Hi @Hughp135, a polyfill sounds like a good idea and shouldn't hurt the API.
I hope that is does not introduce a security vulnerability but as far as I checked it looked good and I can still revert it later in case I am proving wrong.
I went ahead and updated the code to use it, but the CI just threw some weird errors so I'll try to fix them before merging.

Ty for the idea and contribution.

**Comment by AnonymerNiklasistanonym** [comment]
I can't seem to fix the type errors that this import brought with it, not even directly using `whatwg-fetch` works out of the box and custom typings seem to be ignored.
I will check this at a later point, I don't know what the problem of the program is since it actually ran at one point without errors.
If you have any ideas feel free to update this pull request.

**Comment by Hughp135** [comment]
I think that since it's a polyphill, it's not meant to be imported and called instead of fetch. It is only supposed to be imported for the side effect of changing global fetch.

The user of this library may choose their own implementation of fetch depending on their production environment. You can either allow a custom implementation of fetch to be passed into this library, or leave it as it is and let the user polyfill their environment should they need to.

**Comment by AnonymerNiklasistanonym** [comment]
Oh does that mean you meant to only add it to the tests of this library so they can be ran on LTS versions and not the actual library? @Hughp135

**Comment by Hughp135** [comment]
Yeah, pretty much

**Comment by AnonymerNiklasistanonym** [comment]
Oh my bad, I thought because it was listed as dependency it was meant to be part of the package but that makes much more sense.
If listed as dev dependency this should be fine to be merged, I'll remove my bad edits in a second.

Since the package you added seems to be the same as [`whatwg-fetch`](https://www.npmjs.com/package/whatwg-fetch) which is actually still maintained I would probably use that one though or am I missing something?

**Comment by Hughp135** [comment]
However, if you do want to use isomorphic fetch instead of global fetch,
just install the package @types/isomorphic-fetch.

**Comment by AnonymerNiklasistanonym** [comment]
> However, if you do want to use isomorphic fetch instead of global fetch, just install the package @types/isomorphic-fetch.

That was actually the first thing I tried but there seems to be a bug in the type defintion of the package that makes it unable to compile it afterwards.

**Comment by AnonymerNiklasistanonym** [comment]
I think I'm gonna think about it later, your code seems to work fine for now, so I will just add it.
Again ty for your contribution @Hughp135 <3

**Pull request merged**
