### PR TITLE
Users me

### PR DESCRIPTION
**Pull request by Hughp135**
Add function for /users/me endpoint

### CODE REVIEW

**Comment by AnonymerNiklasistanonym** [comment]
I added some basic test cases, documentation and removed that weird type you got for the OAuthAccess token.
If you are fine with that I'll merge it.

**Comment by Hughp135** [comment]
Fine about the type. However I would simplify the type as the endpoint is not concerned with the `expires_in` field of the OAuthAccessToken interface

**Comment by AnonymerNiklasistanonym** [comment]
I found a way to run refresh token tests (at least locally) so I can merge this now.
Ty for your contribution.

**Comment by AnonymerNiklasistanonym** [comment]
> Fine about the type. However I would simplify the type as the endpoint is not concerned with the `expires_in` field of the OAuthAccessToken interface

Sry I kinda missed your comment.
That is pretty true, I'll update the type soon.

**Comment by AnonymerNiklasistanonym** [comment]
@Hughp135 thank you again for the idea <3 (I updated it in c745c531b01568dd906a4ffa791c1183bb3bacad)

**Pull request merged**
