### PR TITLE
Add authorization code grant

### PR DESCRIPTION
**Pull request by Hughp135**
Add functions to obtain a token via authorization code + refresh token

Note: I haven't been able to test this yet, but the only difference between these flows and the client credentials flow is a couple of different fields in the request body and response.

### CODE REVIEW

**Comment by Hughp135** [comment]
> The code looks fine since I remember using that same flow for the Spotify API some months ago. However I'll only add it to the repository when I have tests demonstration that this actually works. I currently am working on something else but as soon as I have time I'll try to write some tests.
> 
> Ty for your contribution and the idea <3

No problem, no rush to merge these in.

Do you want automated tests for this flow (might be a bit difficult / impossible since it involves redirection from the osu website) or would mock testing against the interface be enough? (I will also test the flow manually as I implement it in my project).

**Comment by AnonymerNiklasistanonym** [comment]
I'll for sure will try to automate it somehow but if it's impossible I'll at least want to have an example that I can run locally for testing purposes.

**Comment by AnonymerNiklasistanonym** [comment]
Am I missing something or shouldn't there also be a method that requests the Refresh Access Token Code using the client ID and a redirect URL or is there like a general purpose implementation anywhere?

I'm just asking because in my Spotify API Refresh Token implementation I needed to fetch an authorize endpoint asking for a code given a scope, client ID and the redirect URL which then returned the URL with which the user could approve which then sent the code to my localhost server where I could use the implemented endpoint that requires the code.

It would be great if you could add how you trigger this approval using the client ID and a custom redirect URL.

**Comment by hughp-vv** [comment]
> Do you use a request URL like this: http://osu.ppy.sh/oauth/authorize?client_id=929&redirect_uri=localhost:8080&scope=identify&response_type=code
Yes. A user will follow this kind of URL to the osu website, which they must be logged into in order to authorize themselves. The key here is that they must be logged into the osu website before authorizing your app. This means that automating the whole process isn't really feasible.

Once a user follows the URL and authorizes your app, they get redirected back to your server with the `code` query param. Your server can parse the code and use it to fetch a token on the user's behalf. The code can only be used once before it is rendered invalid.

Your example code works. It is a very simple process since your app only needs to have 1 endpoint for the redirect URI to work.

I am not sure there is anything re-usable that you could add to this library to facilitate the process other than the methods I have already added.

**Comment by Hughp135** [comment]
(Reposting as I was logged in to the wrong account)

Do you use a request URL like this: http://osu.ppy.sh/oauth/authorize?client_id=929&redirect_uri=localhost:8080&scope=identify&response_type=code
Yes. A user will follow this kind of URL to the osu website, which they must be logged into in order to authorize themselves. The key here is that they must be logged into the osu website before authorizing your app. This means that automating the whole process isn't really feasible.

Once a user follows the URL and authorizes your app, they get redirected back to your server with the code query param. Your server can parse the code and use it to fetch a token on the user's behalf. The code can only be used once before it is rendered invalid.

Your example code works. It is a very simple process since your app only needs to have 1 endpoint for the redirect URI to work. You can then do whatever you want with the user's token / refresh token, e.g. save it to a database for later use, verify the user's identity, or "log in" a user to your app/website/service.

I am not sure there is anything re-usable that you could add to this library to facilitate the process other than the methods I have already added.

**Comment by AnonymerNiklasistanonym** [comment]
I was just able to finally reproduce it. Thanks to your comment I realized that my fetch request was stupid since the user should be redirected to the authorize URL and not make a GET request to it.
I'll fix up my changes made and will merge this in some hours.

**Pull request merged**
